[2024-12-06T17:52:52.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T17:52:52.705+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag_v02.wget scheduled__2024-11-02T06:00:00+00:00 [queued]>
[2024-12-06T17:52:52.709+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag_v02.wget scheduled__2024-11-02T06:00:00+00:00 [queued]>
[2024-12-06T17:52:52.709+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T17:52:52.715+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): wget> on 2024-11-02 06:00:00+00:00
[2024-12-06T17:52:52.718+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2487) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T17:52:52.719+0000] {standard_task_runner.py:72} INFO - Started process 2489 to run task
[2024-12-06T17:52:52.720+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag_v02', 'wget', 'scheduled__2024-11-02T06:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpar82b2kc']
[2024-12-06T17:52:52.721+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask wget
[2024-12-06T17:52:52.749+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag_v02.wget scheduled__2024-11-02T06:00:00+00:00 [running]> on host 39ecaeffba2c
[2024-12-06T17:52:52.934+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag_v02' AIRFLOW_CTX_TASK_ID='wget' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-02T06:00:00+00:00'
[2024-12-06T17:52:52.935+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T17:52:52.942+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-06T17:52:52.942+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-11.parquet -O /opt/***/output_2024-11.parquet']
[2024-12-06T17:52:52.948+0000] {subprocess.py:99} INFO - Output:
[2024-12-06T17:52:52.952+0000] {subprocess.py:106} INFO - --2024-12-06 17:52:52--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-11.parquet
[2024-12-06T17:52:52.968+0000] {subprocess.py:106} INFO - Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 18.173.251.90, 18.173.251.37, 18.173.251.196, ...
[2024-12-06T17:52:53.020+0000] {subprocess.py:106} INFO - Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|18.173.251.90|:443... connected.
[2024-12-06T17:52:53.433+0000] {subprocess.py:106} INFO - HTTP request sent, awaiting response... 403 Forbidden
[2024-12-06T17:52:53.434+0000] {subprocess.py:106} INFO - 2024-12-06 17:52:53 ERROR 403: Forbidden.
[2024-12-06T17:52:53.434+0000] {subprocess.py:106} INFO - 
[2024-12-06T17:52:53.435+0000] {subprocess.py:110} INFO - Command exited with return code 8
[2024-12-06T17:52:53.443+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-12-06T17:52:53.446+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=LocalIngestionDag_v02, task_id=wget, run_id=scheduled__2024-11-02T06:00:00+00:00, execution_date=20241102T060000, start_date=20241206T175252, end_date=20241206T175253
[2024-12-06T17:52:53.452+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T17:52:53.453+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task wget (Bash command failed. The command returned a non-zero exit code 8.; 2489)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-12-06T17:52:53.482+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T17:52:53.497+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T17:52:53.500+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
