[2024-12-05T18:08:40.348+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T18:08:40.463+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2024-12-05T18:08:40.503+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2024-12-05T18:08:40.504+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T18:08:40.544+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): ingest> on 2021-01-02 06:00:00+00:00
[2024-12-05T18:08:40.586+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1604) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T18:08:40.588+0000] {standard_task_runner.py:72} INFO - Started process 1634 to run task
[2024-12-05T18:08:40.601+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-01-02T06:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpv83q1ybb']
[2024-12-05T18:08:40.607+0000] {standard_task_runner.py:105} INFO - Job 182: Subtask ingest
[2024-12-05T18:08:40.815+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [running]> on host 073dea24e113
[2024-12-05T18:08:40.915+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-02T06:00:00+00:00'
[2024-12-05T18:08:40.917+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T18:08:40.940+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-05T18:08:40.944+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'pwd"']
[2024-12-05T18:08:40.962+0000] {subprocess.py:99} INFO - Output:
[2024-12-05T18:08:40.964+0000] {subprocess.py:106} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2024-12-05T18:08:40.971+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2024-12-05T18:08:41.007+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T18:08:41.032+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-01-02T06:00:00+00:00, execution_date=20210102T060000, start_date=20241205T180840, end_date=20241205T180841
[2024-12-05T18:08:41.072+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T18:08:41.073+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 182 for task ingest (Bash command failed. The command returned a non-zero exit code 2.; 1634)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T18:08:41.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T18:08:41.147+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T18:08:41.150+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-05T20:36:34.694+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T20:36:34.704+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2024-12-05T20:36:34.709+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2024-12-05T20:36:34.709+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T20:36:34.717+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): ingest> on 2021-01-02 06:00:00+00:00
[2024-12-05T20:36:34.720+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=686) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T20:36:34.722+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-01-02T06:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpfbcmc5p5']
[2024-12-05T20:36:34.724+0000] {standard_task_runner.py:72} INFO - Started process 687 to run task
[2024-12-05T20:36:34.725+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask ingest
[2024-12-05T20:36:34.754+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [running]> on host cf87bc668ac5
[2024-12-05T20:36:34.797+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-02T06:00:00+00:00'
[2024-12-05T20:36:34.797+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T20:36:34.807+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-05T20:36:34.811+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'ls /opt/***']
[2024-12-05T20:36:34.818+0000] {subprocess.py:99} INFO - Output:
[2024-12-05T20:36:34.820+0000] {subprocess.py:106} INFO - ***.cfg
[2024-12-05T20:36:34.821+0000] {subprocess.py:106} INFO - config
[2024-12-05T20:36:34.821+0000] {subprocess.py:106} INFO - dags
[2024-12-05T20:36:34.821+0000] {subprocess.py:106} INFO - logs
[2024-12-05T20:36:34.822+0000] {subprocess.py:106} INFO - output.parquet
[2024-12-05T20:36:34.822+0000] {subprocess.py:106} INFO - output_2021-01.parquet
[2024-12-05T20:36:34.822+0000] {subprocess.py:106} INFO - output_2021-02.parquet
[2024-12-05T20:36:34.822+0000] {subprocess.py:106} INFO - output_2021-03.parquet
[2024-12-05T20:36:34.823+0000] {subprocess.py:106} INFO - output_2021-04.parquet
[2024-12-05T20:36:34.823+0000] {subprocess.py:106} INFO - output_2021-05.parquet
[2024-12-05T20:36:34.823+0000] {subprocess.py:106} INFO - plugins
[2024-12-05T20:36:34.823+0000] {subprocess.py:106} INFO - requirements.txt
[2024-12-05T20:36:34.824+0000] {subprocess.py:106} INFO - webserver_config.py
[2024-12-05T20:36:34.825+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-05T20:36:34.852+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T20:36:34.852+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-01-02T06:00:00+00:00, execution_date=20210102T060000, start_date=20241205T203634, end_date=20241205T203634
[2024-12-05T20:36:34.865+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T20:36:34.879+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T20:36:34.880+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-05T23:10:44.561+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T23:10:44.756+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2024-12-05T23:10:44.762+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2024-12-05T23:10:44.762+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T23:10:44.774+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ingest> on 2021-01-02 06:00:00+00:00
[2024-12-05T23:10:44.780+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T23:10:44.782+0000] {standard_task_runner.py:72} INFO - Started process 127 to run task
[2024-12-05T23:10:44.782+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-01-02T06:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmppexca0cc']
[2024-12-05T23:10:44.785+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask ingest
[2024-12-05T23:10:44.849+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [running]> on host 39ecaeffba2c
[2024-12-05T23:10:44.902+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-02T06:00:00+00:00'
[2024-12-05T23:10:44.903+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T23:10:44.914+0000] {logging_mixin.py:190} INFO - root root pgdatabase 5432 ny_taxi ??? /opt/***/output_2021-01.parquet
[2024-12-05T23:10:44.937+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-05T23:10:44.946+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T23:10:44.948+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-01-02T06:00:00+00:00, execution_date=20210102T060000, start_date=20241205T231044, end_date=20241205T231044
[2024-12-05T23:10:44.963+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T23:10:44.973+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T23:10:44.973+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
