[2024-12-09T23:45:12.341+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T23:45:12.357+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework_dag_v2.download_dataset scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-12-09T23:45:12.364+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework_dag_v2.download_dataset scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-12-09T23:45:12.364+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-09T23:45:12.393+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): download_dataset> on 2021-09-01 00:00:00+00:00
[2024-12-09T23:45:12.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=11803) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T23:45:12.421+0000] {standard_task_runner.py:72} INFO - Started process 11826 to run task
[2024-12-09T23:45:12.419+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'homework_dag_v2', 'download_dataset', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/homework_dag_v2.py', '--cfg-path', '/tmp/tmpj04p6ksz']
[2024-12-09T23:45:12.435+0000] {standard_task_runner.py:105} INFO - Job 161: Subtask download_dataset
[2024-12-09T23:45:12.593+0000] {task_command.py:467} INFO - Running <TaskInstance: homework_dag_v2.download_dataset scheduled__2021-09-01T00:00:00+00:00 [running]> on host 39ecaeffba2c
[2024-12-09T23:45:12.732+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='homework_dag_v2' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2021-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-01T00:00:00+00:00'
[2024-12-09T23:45:12.737+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T23:45:12.748+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-09T23:45:12.749+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'wget https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-01.parquetgreen_tripdata_2021-09.parquet -O /opt/***/green_tripdata_2021-09.parquet']
[2024-12-09T23:45:12.757+0000] {subprocess.py:99} INFO - Output:
[2024-12-09T23:45:12.760+0000] {subprocess.py:106} INFO - --2024-12-09 23:45:12--  https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-01.parquetgreen_tripdata_2021-09.parquet
[2024-12-09T23:45:12.769+0000] {subprocess.py:106} INFO - Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 52.85.39.97, 52.85.39.153, 52.85.39.65, ...
[2024-12-09T23:45:12.784+0000] {subprocess.py:106} INFO - Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|52.85.39.97|:443... connected.
[2024-12-09T23:45:13.117+0000] {subprocess.py:106} INFO - HTTP request sent, awaiting response... 403 Forbidden
[2024-12-09T23:45:13.118+0000] {subprocess.py:106} INFO - 2024-12-09 23:45:13 ERROR 403: Forbidden.
[2024-12-09T23:45:13.119+0000] {subprocess.py:106} INFO - 
[2024-12-09T23:45:13.119+0000] {subprocess.py:110} INFO - Command exited with return code 8
[2024-12-09T23:45:13.133+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-12-09T23:45:13.137+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=homework_dag_v2, task_id=download_dataset, run_id=scheduled__2021-09-01T00:00:00+00:00, execution_date=20210901T000000, start_date=20241209T234512, end_date=20241209T234513
[2024-12-09T23:45:13.145+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T23:45:13.145+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 161 for task download_dataset (Bash command failed. The command returned a non-zero exit code 8.; 11826)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-12-09T23:45:13.174+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-09T23:45:13.190+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T23:45:13.193+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
