[2024-11-29T00:00:49.796+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T00:00:49.803+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T00:00:49.807+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T00:00:49.807+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-29T00:00:49.812+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2024-11-28 00:00:00+00:00
[2024-11-29T00:00:49.815+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=54999) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-29T00:00:49.816+0000] {standard_task_runner.py:72} INFO - Started process 55000 to run task
[2024-11-29T00:00:49.817+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_y1emv_2']
[2024-11-29T00:00:49.819+0000] {standard_task_runner.py:105} INFO - Job 111: Subtask local_to_gcs_task
[2024-11-29T00:00:49.842+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-28T00:00:00+00:00 [running]> on host 4cef807186dc
[2024-11-29T00:00:49.879+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2024-11-29T00:00:49.880+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T00:00:50.424+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-29T00:00:50.439+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T00:00:50.440+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20241129T000049, end_date=20241129T000050
[2024-11-29T00:00:50.456+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-29T00:00:50.470+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-29T00:00:50.471+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
